### ISSUE TITLE
Choose between bokeh and matplotlib for plotting

### ISSUE THREAD

**Issue by ilayn** [ilayn/harold#12]
There are too many cases where bokeh wouldn't work (terminals, IDEs so on) but it is so shiny. I need to get on with it.

**Comment by ilayn** [comment]
Currently, the static bode plot looks like this 
![zzzz](https://cloud.githubusercontent.com/assets/1303842/20697360/dfd9800c-b5f8-11e6-8f98-79d1964ec701.png)

**Comment by Juanlu001** [comment]
Have you tried the release candidate of matplotlib 2.0? Still, I think the interactive plots of Bokeh are very appealing too.

**Comment by ilayn** [comment]
@Juanlu001 I'm actually trying to learn it literally now :) 

Well since I got you here, let me ask for an idea feedback. I'm trying to create a bokeh panel where bode and nyquist is always shown together. What I'm after is to make a mouse hover and as you can see just above in the last plot when you hover over bode nyquist point will be shown with a line segment from the origin to that particular point. Hence as you travel the bode plot the nyquist segment will travel over the nyquist curve. And similarly, if you hover over nyquist you will see the crosshair move in the Bode plots.  

Would that be a useful addition for your taste? I figured that the only way to move people over matlab to any python tool is to play over a bit matlab's staticness. So I'm looking for some polishing features.

**Comment by Juanlu001** [comment]
> I figured that the only way to move people over matlab to any python tool is to play over a bit matlab's staticness.

I 100 % agree with this! The synchronized Bode & Nyquist diagram would be a great addition in my opinion. There are some examples of linked plots in the Bokeh gallery and they look awesome!

I don't have much time to contribute with code nowadays, but I'll be glad to provide feedback and spread the project :smile:

**Comment by ilayn** [comment]
@Juanlu001 perfect. Let me finish a prototype then. Thanks a lot!

**Comment by ilayn** [comment]
@Juanlu001 Here is an initial shot at it :) 

http://nbviewer.jupyter.org/gist/ilayn/f8cf8b0a68c6839dbcc346884511e2ed

Note that everything is super wonky:

  - Phase plot doesn't hover. (I deliberately left it out)
  - For some reason, when hovered the curves go transparent (cool effect though :) )
  - When hovered it actually picks up more than one point
  - Because it's log vs linear plot, most of the bode points are squashed in the ends

and so on ...

But the essential interaction idea is there. And it will revolve around this theme if I can solve the technicalities. Would this be something that is appealing to you and people around you ?

I will ask a few questions to Bokeh people how these issues can be circumvented. If working properly I think I can make preparations for  `harold.interactive`. I have some ideas on using the [Bokeh Tabs](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#tab-panes ) but one step at a time :) 

Thanks again.

**Comment by Juanlu001** [comment]
Wow, this looks cool! I'm actually doing some Bokeh tutorials now, so this arrived for me with perfect timing :) If you raise any issues in the Bokeh issue tracker please @ ping me, I just joined the mailing list too.

I think this has, at least, a great potential for students that are studying control systems. I wish I didn't have to use Simulink back in the days :)

**Comment by ilayn** [comment]
I've asked them in the gitter chat but didn't get any response yet. It's strange that HoverTool for line doesn't have these problems but then it doesn't trigger any callback.

**Comment by ilayn** [comment]
Almost accidentally, I've fixed the multiple selection issue. But the disappearing effect is still there. However, it is much smoother and fancier :) 

The effect is I guess the most dramatic if you follow the phase curve. Thus, a major step forward for my little understanding of Bokeh. 

I've updated the corresponding gist but nbviewer seem not to pick it up properly. in that case you can simply copy/paste from the Gist.

**Comment by Juanlu001** [comment]
Cool! How exactly did you do that? I wonder though if there's some parameter to control the proximity to the line when hovering, feels difficult to follow the path.

**Comment by ilayn** [comment]
I guess linewidth can be increased a bit. It is indeed difficult to stay on the point once hovered.

**Comment by ilayn** [comment]
Bokeh is a bit too funky to rely on in a stable fashion. The tools are deprecated rather too quickly. Might well be worth to keep external examples and code snippets somewhere but it's gonna be matplotlib for now. Also there wasn't too much of a demand for interactivity so I'll just go with the default non-dB y axis and Hz as frequency.
