### ISSUE TITLE
Error converting MIMO transfer function matrix to MIMO State Space realization

### ISSUE THREAD

**Issue by evertoncolling** [ilayn/harold#42]
I am working with MIMO systems analysis. I tried to use harold library to convert a transfer function matrix to a state space realization and found out that there are some problems in this routine.

I attached a jupyter notebook file that reproduces my experiment. I compared the results from harold with python control (and also Matlab, which yelds the same results from python control).

I didn't get the time to read into your code, but due to this issue, the transmission zeros calculation for a MIMO transfer function matrix is getting wrong values as it seems to depend on the state space realization.

[Harold_test.pdf](https://github.com/ilayn/harold/files/2611509/Harold_test.pdf)

**Comment by ilayn** [comment]
I should have tested this branch better. On this line I forgot to invert the array. 

https://github.com/ilayn/harold/blob/master/harold/_classes.py#L2895

I'll fix it, some time today.

**Comment by evertoncolling** [comment]
@ilayn Thanks for looking into the issue so quickly!

I am looking for an LTI package that do not require the slow and cumbersome compilation of SLICOT and your library would really do the job.

And thanks for the reminder regarding the calculation of zeros. I'm starting on this area and on my experience so far I have been working mainly on state space realizations.

**Comment by ilayn** [comment]
I'm just pushing the pull request 😃  Great timing
