### ISSUE TITLE
Shape of D matrix should be p x m or m x p?

### ISSUE THREAD

**Issue by jamestjsp** [ilayn/harold#69]
I ran into an issue while using another package which uses harold, I could solve it by changing to D = np.empty((p, m), dtype=float)  
https://github.com/ilayn/harold/blob/90a785b44f45c9e05a5ef2da935f21c493e8448c/harold/_classes.py#L2883

**Comment by ilayn** [comment]
@jamestjsp Thanks for the report. I'll fix it asap.
