### ISSUE TITLE
This division by sampling time causing wrong dc gain (calculate from impulse response) in the case of discrete system with sampling time other than 1

### ISSUE THREAD

**Issue by jamestjsp** [ilayn/harold#71]
Why this division by sampling time? It's causing a bug in the case of discrete system with sampling time other than 1. I am using impulse response of system for FFT convolve. This division is causing wrong DC gain. Currently I am multiplying sample time to the result of this function to correct DC gain. Is this division really required? 
https://github.com/ilayn/harold/blob/2bfa00fca4549313d47386991a27c84c8fc91637/harold/_time_domain.py#L252

**Comment by ilayn** [comment]
It is a convention of a unit impulse such that the first sample injects a unit = `1./ts * ts=1`. It's not necessary of course but there is a decades of convention behind it.

**Comment by jamestjsp** [comment]
Thank you for the clarification. Closing this issue.

**Comment by ilayn** [comment]
No problem. keep them coming. I'm not always doing the right thing. Thus good to have a fresh pair of eyes
